# Generated by Django 4.1.3 on 2023-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='images/', verbose_name='imagen')),
            ],
        ),
    ]
