# Generated by Django 4.1.3 on 2023-03-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_participantes_remove_evento_pagina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participantes',
            new_name='Participante',
        ),
    ]
