# Generated by Django 4.1.3 on 2023-03-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0006_participante_participa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='participa',
        ),
        migrations.AddField(
            model_name='participante',
            name='participante',
            field=models.CharField(max_length=100, null=True, verbose_name='participante'),
        ),
    ]
