# Generated by Django 4.1.3 on 2023-03-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0007_remove_participante_participa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='participante',
        ),
        migrations.AddField(
            model_name='participante',
            name='participa',
            field=models.CharField(default=1, max_length=100, verbose_name='participa'),
            preserve_default=False,
        ),
    ]
