# Generated by Django 4.1.3 on 2023-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0008_remove_participante_participante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='titulo',
        ),
        migrations.AddField(
            model_name='participante',
            name='nombres',
            field=models.CharField(default=1, max_length=100, verbose_name='nombres'),
            preserve_default=False,
        ),
    ]
