# Generated by Django 4.1.3 on 2023-04-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0009_remove_participante_titulo_participante_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='orden',
            field=models.CharField(max_length=10, null=True, verbose_name='ordenar'),
        ),
    ]
